"""empty message

Revision ID: 1dfefdcaa0dd
Revises: fad7efb9acde
Create Date: 2025-05-02 18:24:57.436372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfefdcaa0dd'
down_revision = 'fad7efb9acde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('who_live_here',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=250), nullable=False))
        batch_op.drop_column('fisrt_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fisrt_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('first_name')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('who_live_here',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
