"""empty message

Revision ID: 512d701fc8fd
Revises: 8a1c0e95d5ad
Create Date: 2025-05-02 18:32:25.816263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512d701fc8fd'
down_revision = '8a1c0e95d5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_who_live_here_fkey', type_='foreignkey')
        batch_op.drop_column('who_live_here')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who_live_here', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('planets_who_live_here_fkey', 'characters', ['who_live_here'], ['characters_id'])

    # ### end Alembic commands ###
