"""empty message

Revision ID: 756486cc7102
Revises: c03a5c075142
Create Date: 2025-05-02 18:38:55.933523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756486cc7102'
down_revision = 'c03a5c075142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('who_live_here',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('who_live_here',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
