"""empty message

Revision ID: 808993ba34e1
Revises: 512d701fc8fd
Create Date: 2025-05-05 17:22:42.715520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808993ba34e1'
down_revision = '512d701fc8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who_live_here', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'characters', ['who_live_here'], ['characters_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('who_live_here')

    # ### end Alembic commands ###
