"""empty message

Revision ID: 9d7b5c6833c4
Revises: 4a0a547d14b4
Create Date: 2025-05-02 18:27:35.690749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7b5c6833c4'
down_revision = '4a0a547d14b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=250), nullable=False))
        batch_op.drop_column('fisrt_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fisrt_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
