"""empty message

Revision ID: c03a5c075142
Revises: cf23fb93c2e2
Create Date: 2025-05-01 17:52:18.029582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03a5c075142'
down_revision = 'cf23fb93c2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=250), nullable=False))
        batch_op.drop_column('fisrt_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fisrt_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
