"""empty message

Revision ID: f3cb41c99da6
Revises: 9d7b5c6833c4
Create Date: 2025-05-02 18:38:35.174078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cb41c99da6'
down_revision = '9d7b5c6833c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('who_live_here',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('who_live_here',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
